USE [SistemaObrero]
GO

/****** Object:  Table [dbo].[MarcasDeAsistencia]    Script Date: 06/05/2021 19:46:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MarcasDeAsistencia](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MarcaInicio] [varchar](64) NOT NULL,
	[MarcaFin] [varchar](64) NOT NULL,
 CONSTRAINT [PK_MarcasDeAsistencia] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

